worker_processes  1;

events {
    worker_connections  1024;
}

rtmp {
    server{
        listen 1935;
        chunk_size 4096;
        # buflen 1s;

        # 主应用 - 接收所有边缘端的推流
        application live {
            live on;
            record off;
            idle_streams off;

            gop_cache on;
            wait_key on;
            wait_video on;

            allow play all;
            allow publish all;

            push_reconnect 1s;  # 转发失败后 1秒重试
        }
    }
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;  # 禁用Nagle算法，减少延迟

    keepalive_timeout  65;

    server {
        listen       80;
        server_name  122.51.125.235;

        set $local_cpp_server http://127.0.0.1:2250;

        # HTTP-flv拉流地址
        location /flv {
            flv_live on;  # 开启HTTP-FLV
            chunked_transfer_encoding off;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

        }

        location /live {
            flv_live on;
            chunked_transfer_encoding on;
            
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            add_header Cache-Control no-cache;

            proxy_buffering off;
        }

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
            add_header Access-Control-Allow-Origin *;
        }

        # 前端消息转发
        location / {
            proxy_pass $local_cpp_server;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 超时设置
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
    }

}