worker_processes  1;

events {
    worker_connections  1024;
}

rtmp{
    server{
        listen 1935;
        chunk_size 4096;
        buflen 1s;

        # 主应用 - 接收所有边缘端的推流
        application live {
            live on;
            record off;  # 先关闭录制

            allow publish all;
            allow play all;

            # on_publish http://localhost:80/auth_publish;
            # on_play http://localhost:80/auth_play;

            push rtmp://localhost:1935/flv;  # 转发到flv流，即下面的flv应用
        }

        # http-flv应用
        application flv {
            live on;
            record off;  

            allow play all;
            # pull rtmp://localhost:1935/live name=live static;
        }

        application health{
            live on;
            record off;
        }
    }
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  122.51.125.235;

        set $local_cpp_server http://127.0.0.1:2250;
        # HTTP-flv拉流地址
        location /flv {
            flv_live on;  # 开启HTTP-FLV
            chunked_transfer_encoding on;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        }

        location ~ ^/live/(.*)$ {
            flv_live on;
            add_header Access-Control-Allow-Origin *;
            add_header Cache-Control no-cache;

            # 流访问格式： /live?app=flv_stream&stream={camera_id}
        }

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
            add_header Access-Control-Allow-Origin *;
        }

        # 前端消息转发
        location / {
            proxy_pass $local_cpp_server;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 超时设置
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
    }

}